title: robot-face
hero_image: images/banner.png
description: robot-face description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Test your machine learning model
  - title: Use emoji for your robot face
  - title: Making a face
  - title: Adding the eyes
  - title: Adding the Raspberry Pi
  - title: Motorising the mouth
  - title: Programming the eyebrows
  - title: Programming the eyes
  - title: Changing faces
  - title: Emotional responses to objects
  - title: What next?
