title: robot-face
hero_image: images/banner.png
description: robot-face description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Recognising Objects
  - title: Getting Expressive
  - title: Making a face
