title: robot-face
hero_image: images/banner.png
description: robot-face description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-26"
steps:
  - title: Introduction
  - title: Test your machine learning model
  - title: Use emoji for your robot face
  - title: Make a face
  - title: Add the eyes
  - title: Add the Raspberry Pi
  - title: Motorise the mouth
  - title: Program the eyebrows
  - title: Program the eyes
  - title: Changing faces
  - title: Emotional responses to objects
  - title: What next?
