---
title: LEGO®ロボットの顔
hero_image: images/banner.png
description: LEGO®とBuildHATで見えるものに反応するロボットの顔を作成します
version: 4
listed: true
copyedit: true
last_tested: "2020-02-26"
steps:
  - 
    title: はじめに
  - 
    title: 機械学習モデルをテストする
  - 
    title: ロボットの顔に絵文字を使用する
  - 
    title: 顔を作る
  - 
    title: 目を追加する
  - 
    title: ラズベリーパイを追加する
  - 
    title: 口を動かす
  - 
    title: 眉毛をプログラムする
  - 
    title: 目をプログラムする
  - 
    title: 顔を変える
  - 
    title: オブジェクトに対する感情的な反応
  - 
    title: 次は何をしますか？
